# ── Gradle plugins ────────────────────────────────────────────────────────────
foojayVersion=0.8.0
springBootVersion=3.3.4
springDependencyManagementVersion=1.1.6
jibVersion=3.4.3
protobufPluginVersion=0.9.4

# ── Java ───────────────────────────────────────────────────────────────────────
javaVersion=21

# ── Dependencies ───────────────────────────────────────────────────────────────
postgresqlVersion=42.7.4
protobufVersion=3.25.5
springdocVersion=2.6.0
vertxVersion=4.5.9

# ── Docker base images ─────────────────────────────────────────────────────────
jreImage=eclipse-temurin:21-jre-alpine
nginxImage=nginx:alpine

# ── Docker client ──────────────────────────────────────────────────────────────
dockerExecutable=/usr/bin/docker
