apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-client
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql-client
  template:
    metadata:
      labels:
        app: psql-client
    spec:
      containers:
        - name: psql
          image: {{ .Values.psqlClient.image }}
          command: ["sleep", "infinity"]
          env:
            - name: PGHOST
              value: {{ .Values.psqlClient.risingwaveHost }}
            - name: PGPORT
              value: "{{ .Values.psqlClient.risingwavePort }}"
            - name: PGUSER
              value: root
            - name: PGDATABASE
              value: dev
            - name: PGPASSWORD
              value: ""
