apiVersion: apps/v1
kind: Deployment
metadata:
  name: risingwavepoc-rw-loader
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risingwavepoc-rw-loader
  template:
    metadata:
      labels:
        app: risingwavepoc-rw-loader
    spec:
      containers:
        - name: rw-loader
          image: {{ .Values.app.image }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
