apiVersion: apps/v1
kind: Deployment
metadata:
  name: rw-server
  namespace: risingwavepoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rw-server
  template:
    metadata:
      labels:
        app: rw-server
    spec:
      containers:
        - name: risingwave
          image: risingwavelabs/risingwave:latest
          args: ["playground"]
          ports:
            - name: sql
              containerPort: 4566
            - name: dashboard
              containerPort: 5691
---
apiVersion: v1
kind: Service
metadata:
  name: rw-server
  namespace: risingwavepoc
spec:
  selector:
    app: rw-server
  ports:
    - name: sql
      port: 4566
      targetPort: 4566
    - name: dashboard
      port: 5691
      targetPort: 5691
